ToDo/Models/ErrorViewModel.cs
using System;

namespace ToDo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDo/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDo.Models
{
    public enum Color
    {
        RED,
        BLUE,
        GREEN,
        YELLOW,
        WHITE
    }
    
    public class Note
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Details { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [StringLength(250, ErrorMessage = "Title should not contain more than 250 characters")]
        public string Title { get; set; }
        public Color Color { get; set; }
        public string DateCreated { get; set; }

        public Note()
        {
            DateCreated = DateTime.UtcNow.ToString("MMM d, yyyy - h:mm tt");
        }
    }
}

ToDo/Models/_Task.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDo.Models
{
    public enum Color
    {
        RED,
        BLUE,
        GREEN,
        YELLOW,
        WHITE
    }
    
    public class _Task
    {
        public int ID { get; set; }
        public string Details { get; set; }
        public string Title { get; set; }
        public Color Color { get; set; }
        public string DateCreated { get; set; }

        public _Task()
        {
            DateCreated = DateTime.UtcNow.ToString("MMM d, yyyy - h:mm tt");
        }
    }
}

ToDo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ToDo.Models;

namespace ToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDo/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ToDo.Data;
using ToDo.Models;

namespace ToDo.Controllers
{
    public class NoteController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public NoteController(ApplicationDbContext db)
        {
            dbContext = db;
        }

        // Action to view all Notes
        public IActionResult Index()
        {
            IEnumerable<Note> Notes = dbContext.Notes;
            return View(Notes);
        }

        // Action to Add New Notes - GET - What to do before user presses the submit button
        public IActionResult Add()
        {
            return View();
        }

        // Action to Add New Notes - POST - What the app does after the submit button
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Note obj)
        {
            if (ModelState.IsValid)
            {
                dbContext.Notes.Add(obj);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // Action to Get Task Details
        public IActionResult Details(int? ID)
        {
            // Constraint to make ID greater than 0
            if (ID == null || ID == 0)
            {
                return NotFound();
            }

            // Find Notes by ID
            var task = dbContext.Notes.Find(ID);
            if (task is null)
            {
                return NotFound();
            }

            return View(task);
        }

        // Action to Get Task and Edit
        public IActionResult Edit(int? ID)
        {
            // Constraint to make ID greater than 0
            if (ID == null || ID == 0)
            {
                return NotFound();
            }

            // Find Notes by ID
            var task = dbContext.Notes.Find(ID);
            if (task is null)
            {
                return NotFound();
            }

            return View(task);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Note obj)
        {
            if (ModelState.IsValid)
            {
                dbContext.Notes.Update(obj);
                dbContext.SaveChanges();
                return RedirectToAction("Details", new { id = obj.ID });
            }

            return View(obj);
        }

        // Action to GET Notes for Delete
        public IActionResult Delete(int? ID)
        {
            // Constraint to make ID greater than 0
            if (ID == null || ID == 0)
            {
                return NotFound();
            }

            // Find Notes by ID
            var task = dbContext.Notes.Find(ID);
            if (task is null)
            {
                return NotFound();
            }

            return View(task);
        }

        // Action to find Notes for Delete - POST
        public IActionResult DeleteNote(int? ID)
        {
            var obj = dbContext.Notes.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            dbContext.Notes.Remove(obj);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ToDo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDo/Views/Note/Add.cshtml
@model ToDo.Models.Note
@{
    ViewData["Title"] = "Add Note";
    Dictionary<Color, string> colors = new Dictionary<Color, string> {
        { Color.RED, "Red"},
        { Color.BLUE, "Blue" },
        { Color.GREEN, "Green" },
        { Color.YELLOW, "Yellow" },
        { Color.WHITE, "White" }
    };
}

<form asp-action="Add" method="post">
    <div class="jumbotron col-8">

        <div class="form-group">
            <h2 class="text-info">Add Note</h2>
        </div>

        <div class="pt-2">
            <div class="form-group">
                <div>
                    <h4><label asp-for="Title"></label></h4>
                </div>

                <div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                    <input asp-for="Title" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <div>
                    <h4><label asp-for="Details"></label></h4>
                </div>

                <div>
                    <span asp-validation-for="Details" class="text-danger"></span>
                    <textarea asp-for="Details" class="form-control" rows="4"></textarea>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <h4><label asp-for="Color"></label></h4>
                </div>

                <div class="mt-n2">
                    @foreach (var color in colors.Keys)
                    {
                        @Html.RadioButtonFor(Model => Model.Color, color) <span>  @colors[color]</span> <br />
                    }
                    
                </div>
            </div>

            <div>
                <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
                <input class="btn btn-outline-primary float-right" type="submit" value="Add">
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial"} /> }
}

ToDo/Views/Note/Delete.cshtml
@model ToDo.Models.Note
@{
    ViewData["Title"] = "Edit Note";
    Dictionary<Color, string> colors = new Dictionary<Color, string> {
        { Color.RED, "Red"},
        { Color.BLUE, "Blue" },
        { Color.GREEN, "Green" },
        { Color.YELLOW, "Yellow" },
        { Color.WHITE, "White" }
    };
}

<form asp-action="DeleteNote" method="post">
    <input asp-for="ID" type="hidden" />
    <div class="jumbotron col-8">

        <div class="form-group">
            <h2 class="text-info">Delete</h2>
        </div>

        <div class="pt-2">
            <div class="form-group">
                <div>
                    <h4><label asp-for="Title"></label></h4>
                </div>

                <div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                    <input asp-for="Title" class="form-control"  disabled/>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <h4><label asp-for="Details"></label></h4>
                </div>

                <div>
                    <span asp-validation-for="Details" class="text-danger"></span>
                    <textarea asp-for="Details" class="form-control" rows="4" disabled></textarea>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <h4><label asp-for="Color"></label></h4>
                </div>

                <div class="mt-n2">
                    @foreach (var color in colors.Keys)
                    {
                        @Html.RadioButtonFor(Model => Model.Color, color, new { disabled = true}) <span>  @colors[color]</span> <br />
                    }

                </div>
            </div>

            <div>
                <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
                <input class="btn btn-outline-primary float-right" type="submit" value="Delete">
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" } />
    }
}

ToDo/Views/Note/Details.cshtml
@model ToDo.Models.Note
@{
    ViewData["Title"] = Model.Title;
}

<div class="jumbotron">
    <h3 class="display-4">@Model.Title</h3>
    <p class="small text-secondary">@Model.DateCreated</p>
    <hr />

    <article>
        @Model.Details
    </article>

    <footer class="float-left">
        <a class="btn btn-secondary" asp-action="Index">Back</a>
        <div class="float-right">
            @Html.ActionLink("Edit", "Edit", "Note", new { id = Model.ID }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Delete", "Delete", "Note", new { id = Model.ID }, new { @class = "btn btn-danger rounded-sm" })
            </div>
    </footer>
</div>

ToDo/Views/Note/Edit.cshtml
@model ToDo.Models.Note
@{
    ViewData["Title"] = "Edit Note";
    Dictionary<Color, string> colors = new Dictionary<Color, string> {
        { Color.RED, "Red"},
        { Color.BLUE, "Blue" },
        { Color.GREEN, "Green" },
        { Color.YELLOW, "Yellow" },
        { Color.WHITE, "White" }
    };
}

<form asp-action="Edit" method="post">
    <input asp-for="ID" type="hidden" />
    <div class="jumbotron col-8">

        <div class="form-group">
            <h2 class="text-info">Edit Note</h2>
        </div>

        <div class="pt-2">
            <div class="form-group">
                <div>
                    <h4><label asp-for="Title"></label></h4>
                </div>

                <div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                    <input asp-for="Title" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <div>
                    <h4><label asp-for="Details"></label></h4>
                </div>

                <div>
                    <span asp-validation-for="Details" class="text-danger"></span>
                    <textarea asp-for="Details" class="form-control" rows="4"></textarea>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <h4><label asp-for="Color"></label></h4>
                </div>

                <div class="mt-n2">
                    @foreach (var color in colors.Keys)
                    {
                        @Html.RadioButtonFor(Model => Model.Color, color) <span>  @colors[color]</span> <br />
                    }

                </div>
            </div>

            <div>
                <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
                <input class="btn btn-outline-primary float-right" type="submit" value="Save">
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" } />
    }
}

ToDo/Views/Note/Index.cshtml
@model IEnumerable<ToDo.Models.Note>
@{
    ViewData["Title"] = "Notes";
}

<div class="jumbotron">

    @Html.ActionLink("Add Note", "Add", "Note", null, new { @class = "btn btn-primary rounded-sm float-right mt-n4" })
    <br />
    <hr />

    @if (Model.Count() == 0)
    {
        <h3 class="display-4 pt-2">You have no notes yet.</h3>
    }
    else
    {
        foreach (var note in Model)
        {
            <div class="container list-inline">
                <div class="list-inline-item">
                    <h3>@Html.ActionLink(note.Title, "Details", new { id = note.ID}, new { @class = "text-decoration-none", style = "color: black;" })
                        <span style="background-color: @note.Color.ToString()" class="badge">@note.Color.ToString().Substring(0, 1).ToUpper()@note.Color.ToString().Substring(1).ToLower()
                        </span>
                    </h3>
                    <p class="small text-secondary">@note.DateCreated</p>
                </div>
                <div class="float-right list-inline-item pt-2">
                    @Html.ActionLink("Edit", "Edit", "Note", new { id = note.ID }, new { @class = "btn btn-primary rounded-sm" })
                    @Html.ActionLink("Delete", "Delete", "Note", new { id = note.ID }, new { @class = "btn btn-danger rounded-sm" })
                </div>
            </div>
            <hr />
        }
    }
</div>

ToDo/Views/Shared/DeletePartial.cshtml
@model ToDo.Models.Note

<div class="modal fade" id="foo" tabindex="-1" role="alertdialog" aria-labelledby="DeleteTaskLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="DeleteTaskLabel">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                This task will be deleted permanently. Continue?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form method="post" asp-action="DeleteTask">
                    <input type="submit" class="btn btn-danger" value="Delete" />
                </form>
            </div>
        </div>
    </div>
</div>

ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Notes</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>